instruments:
  - instrument_id: "XHKG:2603"
    mic: "XHKG"
    feedcode: "2603"
    trading_currency_id: "HKD"
    tick_size: "0.01"
    lot_size: 100
  - instrument_id: "XHKG:2330"
    mic: "XHKG"
    feedcode: "2330"
    trading_currency_id: "HKD"
    tick_size: "0.01"
    lot_size: 100