instruments:
  - instrument_id: "2603"
    mic: "XTAI"
    feedcode: "2603"
    trading_currency_id: "TWD"
    tick_size: "50"
    lot_size: 1
  - instrument_id: "2330"
    mic: "XTAI"
    feedcode: "2330"
    trading_currency_id: "TWD"
    tick_size: "100"
    lot_size: 1
